# See https://hub.docker.com/_/mariadb

# See README.md

# sudo docker network inspect csvuploader_default

# sudo docker-compose -f Dockerfile up
# sudo docker exec -it csvuploader_db /bin/bash
# mysql -uroot -ppassword
# show databases;
# use csvuploader;
# show tables;

version: '3.1'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: csvuploader_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - csvuploader_default

  webserver:
    image: nginx:alpine
    container_name: csvuploader_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - csvuploader_default

  csvuploader_db:
    image: mariadb
    #build:
    #  context: ./csvuploader_db/
    #  dockerfile: ../Dockerfile
    restart: always
    #hostname: csvuploader.localhost.com
    hostname: localhost
    ports:
      - 3306:3306
    expose:
      - 3306
    container_name: csvuploader_db
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE} # CREATE DATABASE csvuploader;
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD} # CREATE USER 'csvuploader' IDENTIFIED BY 'password'; GRANT ALL ON *.* TO 'csvuploader'@'%';
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      # - csvuploader_db:/var/lib/mysql
      # - ./db:/var/lib/mysql
      - ./database/db:/docker-entrypoint-initdb.d
    networks:
      csvuploader_default:
      #ipv4_address: 172.18.0.1

#volumes:
#  redis-data:
#  csvuploader_db:

networks:
  csvuploader_default:
  #ipam:
  #driver: default
  #config:
  #  - subnet: 172.18.0.0/16
