# See https://hub.docker.com/_/mariadb

# See README.md

# sudo docker network inspect csvuploader_default

# sudo docker-compose -f Dockerfile up
# sudo docker exec -it csvuploader_db /bin/bash
# mysql -uroot -ppassword
# show databases;
# use csvuploader;
# show tables;

version: '3'
services:
  # React SPA
  spa:
    #hostname: spa.csvuploader.localhost.com
    container_name: csvuploader_spa
    build:
      context: .
      dockerfile: ./spa.Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - './SPA/:/app/' # mirror ./SPA to container app folder
      - '/app/node_modules'
    ports:
      - 80:80
      - 443:443
      - 3001:3000 # poke a hole for npm run start
    expose:
      - 80
      - 443
    environment:
      - CHOKIDAR_USEPOLLING=true # for hot reload
      - REACT_APP_API_URL=http://localhost::8000/api
    depends_on:
      - db
      - api

  # Laravel API
  api:
    container_name: csvuploader_api
    #hostname: api.csvuploader.localhost.com
    build:
      context: .
      dockerfile: ./api.Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    ports:
      - 8001:8000 # poke a hole for artisan run serve
      - 8000:80
    expose:
      - 80
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    depends_on:
      - db

  # MariaDB DB
  db:
    #hostname: db.csvuploader.localhost.com
    hostname: localhost
    container_name: csvuploader_db
    build:
      context: .
      dockerfile: ./db.Dockerfile
    #image: mariadb
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE} # CREATE DATABASE csvuploader;
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD} # CREATE USER 'csvuploader' IDENTIFIED BY 'password'; GRANT ALL ON *.* TO 'csvuploader'@'%';
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      # - csvuploader_db:/var/lib/mysql
      # - ./db:/var/lib/mysql
      - ./database/db:/docker-entrypoint-initdb.d

#volumes:
#  redis-data:
#  csvuploader_db:
